In [2]:
import numpy as np


1. array()

    The array() function is used to create a NumPy array from a list.

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
#How to convert list into Array

my_list = [[10, 20, 30, 40,50],[60,70,80,90,100]]
arr = np.array(my_list)

print(arr)
print(type(arr))


[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
<class 'numpy.ndarray'>


2. zeros()

     The zeros() function creates an array filled with zeros. 

In [10]:
#Syantex-
    # np.zeros(size)
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


3. ones()

    The ones() function creates an array filled with ones.

In [11]:
import numpy as np

arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


In [12]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]
